// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6z5iiJ8YR6fidK1cMpqp42abOgzpbA5E',
    appId: '1:546058026320:web:ca2404d1ef58e835f10055',
    messagingSenderId: '546058026320',
    projectId: 'iwi-bulletinboard',
    authDomain: 'iwi-bulletinboard.firebaseapp.com',
    storageBucket: 'iwi-bulletinboard.appspot.com',
    measurementId: 'G-SG9C4RSDGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOlpjehWzfM6lCKkm_S5AeHC7N6qWYT4',
    appId: '1:546058026320:android:677a2552144ef6cff10055',
    messagingSenderId: '546058026320',
    projectId: 'iwi-bulletinboard',
    storageBucket: 'iwi-bulletinboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0BE0Tr4RVirFnkCsWeFlGsTst_txcTA',
    appId: '1:546058026320:ios:73ff3229f348ef3ff10055',
    messagingSenderId: '546058026320',
    projectId: 'iwi-bulletinboard',
    storageBucket: 'iwi-bulletinboard.appspot.com',
    iosBundleId: 'com.lrprojects.iwiBulletinboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0BE0Tr4RVirFnkCsWeFlGsTst_txcTA',
    appId: '1:546058026320:ios:d524cf8daf310914f10055',
    messagingSenderId: '546058026320',
    projectId: 'iwi-bulletinboard',
    storageBucket: 'iwi-bulletinboard.appspot.com',
    iosBundleId: 'com.lrprojects.iwiBulletinboard.RunnerTests',
  );
}
